// <auto-generated />
using BulmaTutorial.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BulmaTutorial.Migrations
{
    [DbContext(typeof(ExampleContext))]
    partial class ExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BulmaTutorial.Models.BulmaExample", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Brand = "DiGiorno",
                            Category = "Fats",
                            Cost = 6,
                            Food = "Pepperoni Pizza"
                        },
                        new
                        {
                            ID = 2,
                            Brand = "Kellog",
                            Category = "Cereal",
                            Cost = 3,
                            Food = "Frosted Flakes"
                        },
                        new
                        {
                            ID = 3,
                            Brand = "Country Fresh",
                            Category = "Vegetables",
                            Cost = 2,
                            Food = "Carrot Sticks"
                        },
                        new
                        {
                            ID = 4,
                            Brand = "Driscoll's",
                            Category = "Fruits",
                            Cost = 4,
                            Food = "Strawberries"
                        },
                        new
                        {
                            ID = 5,
                            Brand = "Tyson",
                            Category = "Protein",
                            Cost = 5,
                            Food = "Chicken Nuggets"
                        },
                        new
                        {
                            ID = 6,
                            Brand = "Frito Lay",
                            Category = "Fats",
                            Cost = 3,
                            Food = "Doritos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
